version: "3"
services: 
  db:
    container_name: bitmex_database
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: bitmex123456
      POSTGRES_USER: svc_bitmexbitmex
      POSTGRES_DB: database_bitmex
    volumes:
      - pgdata:/var/lib/postgresql/data
  app:
    container_name: bitmex
    restart: always
    build: . 
    ports:
      - 2000:2000
    volumes:
      - .:/usr/src/app
    depends_on:
      - db 
volumes:
  pgdata:      